
description: >
  Hackerspaces in Finland
github_username: hacklab-fi

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

title_prefix: "hacklab.fi | "

paginate: 99
paginate_path: "blog/page:num/"
# if blog posts get paginated to next page, english version index page does not work
# this could be fixes using jekyll-paginate-multiple (or manual edits)
# -- paginate multiple is not supported by github pages....
